### ISSUE TITLE
Your homepage fails to restore my Safari scrolling to top

### ISSUE THREAD

**Issue by irae** [layerJS/layerJS#76] opened 2018-05-10 16:06 UTC
![screen shot 2018-05-10 at 1 03 54 pm](https://user-images.githubusercontent.com/98254/39880038-e6121f5c-5452-11e8-86f7-9ff25a8ed70c.png)

I can't scroll to the top anymore. I only scrolled down and played the animation

**Comment by thomashandorf** [comment] 2018-05-10 19:43
@irae thanks for reporting. Do you know how to reproduce this. Can't see it on my safari. Which version are you using? could be a relapse of #54

**Comment by irae** [comment] 2018-05-11 19:48
Safari Version 11.1 (13605.1.33.1.4)

I have content blockers, if it makes any sense to mention. The one I use is called "Better". Except for that I don't have anything in special.

The way I reproduce every time:
1. enter page, scroll down
2. hit play on the "video" or animation, the one that shows a 3d view of layers. I think video/animation still playing when I scroll.
3. Scroll up kinda fast, my mouse is one of those with an actual scroll wheel, so I don't have the smooth ease in and out the apple mouse or trackpad does.

Just got a different version of the bug:
<img width="1448" alt="screen shot 2018-05-11 at 4 44 24 pm" src="https://user-images.githubusercontent.com/98254/39943901-fb26e4c0-553a-11e8-997a-a56abd48a9e2.png">

I did my own scrolling/layering library in the past, so if I had to guess I would say you might be doing some delta bookkeeping somewhere and if some event drops you can't get the math right. It is either Safari trying to be smart and make my scroll smooth, or you tested with smooth and mine has none.

**Comment by thomashandorf** [comment] 2018-05-13 10:05
found the problem. A secondary script on the landing page did set a transition property on the frame. This is a problem for layerJS during a transition as it will not receive the transitionEnd event. This is now fixed on the landing page but the issue will remain open until there is a way to catch missing transitionEnd event by a fallback timer.

**Comment by irae** [comment] 2018-05-14 13:16
Is this by spec? Or should the `transitionEnd` be accessible by layerJS? If this is not by spec and happening only on Safari, you could totally file a bug on webkit. If this is on all browsers, well, then it's a layerJS problem, I guess?

My 5¢: I remember not being able to rely on `trnsitionEnd` when I was trying to fix `ReactTransitionGroup` back in 2014 or so. It is quite a finicky API. Did you try to bind `transitionEnd` on the capture phase on the `document`? I wouldn't interact with the event at this stage (specially because since developers rarely rely on capture phase it makes it quite uneven across browsers), but you might be able get read only reliable information. But at least you could set up your own cleanup timer.

Also, maybe file another bug with more technical details and close this? Might be more organized, since now it is not related to the homepage anymore.

**Comment by thomashandorf** [comment] 2018-05-14 20:16
it suppose it's rather a bug in the spec. When something is setting the transition of the transform while the transition is ongoing, the transition is stopped immediately and no transitionEnd will fire. There is a transitionCancel but that seems to be implemented only by Mozilla. I haven't played with the capture phase here, but i think that the event is just not fired at all in this case. 

This wasn't a Safari only issue. i was able to reproduce it on chrome as well.

**Comment by kennytordeur** [comment] 2018-06-18 11:56
This got fixed in 0ba93452a3ec0198fdea04802efcf26f5d1382cb

**Closed as completed by kennytordeur** 2018-06-18 11:56 UTC
