### ISSUE TITLE
if no frame data-el-name is given layers fails

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#29] opened 2016-11-10 13:39 UTC
the following code fails:
```
<body data-wl-type="stage">
  <div data-wl-type="layer" data-wl-layout="canvas">
    <div data-wl-type="frame" data-wl-fit-to="width">
…
```

even though frames need names to be changeable there may be stages that have only one frame in which case no name is needed. 

not sure what to do with this for now. A minor issue anyway\
\
Originally created at 2016-06-07 12:53:53+00:00 (UTC) by thomashandorf as a(n) minor issue.

**Comment by thomashandorf** [comment] 2016-11-12 10:10
duplicate of #41

**Closed as completed by thomashandorf** 2016-11-12 10:10 UTC
Labels: bug, duplicate, bitbucket-migrated, Transition Code / Layer Layouts, prio:low
